import { Header } from '@/components/Header'
import { Footer } from '@/components/Footer/Footer';


import './globals.css'
import 'react-toastify/dist/ReactToastify.css';


export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
  
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">

      <body>
        <Header/>
        {children}
        

      <Footer/>
        </body>
    </html>
  )
}
