import '../styles/globals.css';
import Head from 'next/head';
import Header from '../components/navigation/Header';
import { SessionProvider } from 'next-auth/react';
import Footer from '../components/footer';

function MyApp({ Component, pageProps }) {
	return (
		<SessionProvider session={pageProps.session}>
			<Head>
				<title>Create Next App</title>
				<meta name='description' content='Generated by create next app' />
				<link rel='icon' href='/favicon.ico' />
			</Head>
			<Header />
			<Component {...pageProps} />
			<Footer />
		</SessionProvider>
	);
}

export default MyApp;
