import '../styles/globals.css';
import Head from 'next/head';
import Header from '../components/navigation/Header';
import { SessionProvider } from 'next-auth/react';
import Footer from '../components/footer';
import { useRouter } from 'next/router';

function MyApp({ Component, pageProps }) {
	const router = useRouter();
	return (
		<SessionProvider session={pageProps.session}>
			<Head>
				<title>Google V3</title>
				<meta name='description' content='Generated by create next app' />
				<link rel='icon' href='/favicon.ico' />
			</Head>
			{router.pathname.startsWith('http://localhost:3000/search?') && (
				<Header />
			)}
			<Component {...pageProps} />
			<Footer />
		</SessionProvider>
	);
}

export default MyApp;
