import '../globals.css';
import 'react-toastify/dist/ReactToastify.css';
import { SearchHeader } from '@/components/SearchHeader';

export const metadata = {
	title: 'SearchPage',
	description: 'Generated by create next app',
};

export default function SearchLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		
			<main>
				<SearchHeader/>
				{children}

				
			</main>
		
	);
}
